language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)

before_install:
 - sudo apt-get install -y cabal-install shunit2
 - cabal update
 - cabal install shellcheck

script:
 - bash -c 'shopt -s globstar; shellcheck **/*.sh'

matrix:
  fast_finish: true
